name = "Io Levoi"
license = "MIT"
licenselink = "https://github.com/lgaida/mediumish-theme-gohugo/blob/master/LICENSE"
description = "The online home of Io Levoi"
homepage = "http://lgaida.de"
tags = ["Blog", "Writer", "Personal Knowledge", "Van Life", "Google Analytics"]
features = []
min_version = "0.41"

[author]
  name = "Io"
  homepage = "http://lgaida.de"

# If porting an existing theme
[original]
  name = "wowthemesnet"
  homepage = "https://www.wowthemes.net/"
  repo = "https://github.com/wowthemesnet/mediumish-theme-jekyll"
